#!/bin/bash
sudo apt update
sudo apt install apache2
sudo apt install php8.3-mysql php8.3-mbstring php8.3-xml php8.3 curl
sudo service apache2 status
sudo systemctl enable apache2
sudo apt install mysql-client
